### ISSUE TITLE
Merging sometimes does a double merge

### ISSUE THREAD

**Issue by nlowe** [techwiz24/2048fx#1]
For example, moving `[4, 2, 2, 0]` to the right yields `[0, 0, 0, 8]`, not `[0, 0, 4, 4]`

Only affects Right and Down

**Comment by techwiz24** [comment]
Doesn't seem to affect left, up, or down

**Comment by nlowe** [comment]
Seems to be fine in [the text-based version](https://github.com/techwiz24/eecs1510-2048/blob/master/src/eecs1510/Game/Board.java#L89), I guess I'll just re-implement the merging algorithm. Must have broke it when i was trying to simplify things
